### ISSUE TITLE
About dataset selection issue

### ISSUE THREAD

**Issue by dong-ai-7** [houcharlie/PrE-Text#2]
Hi~ Can you provide the download and processing method for datasets, such as  c4-English in "PrE-Text: Training Language Models on Private Federated Data in the Age of LLMs"?

**Comment by houcharlie** [comment]
Hi, unfortunately we aren't allowed to provide the precise dataset or the processing code. But you can choose your own website you would like to filter for from c4-english https://huggingface.co/datasets/allenai/c4 to test on your own dataset  (i.e. filter for samples with 'wikipedia' in the url column if you want wikipedia text).
